# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTI5NjAxMDZlNWEyYWM2ZjBhOTk5OTkyZDM3OTEyYTAzY2QyNDcxZTZmYTQxODBjZmNiZmYwMDQ4Njc2N2U5OTc3NWMzMjYzOGEyMzZmOGViMDk2NzgwZTYyN2Q4ZTU2MWQzYTliYmY1MWNiNzU4NmY0YjdlYTFiNTQ5Y2Q1OTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
